root: true
env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'
  - '@nuxtjs'
  - 'plugin:nuxt/recommended'
# parser: 'vue-eslint-parser'
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - vue
rules:
  ignoreRestSiblings: 1
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
settings:
  'import/resolver': {
    nuxt: {
      extensions: ['.js', '.vue'],
    }
  }